# syntax=docker/dockerfile:1.3
# ******************
#  Copyright 2025 Sean M. Brennan and contributors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ******************

# Runs automated testing for AutonomousTrust

# Build from repo base dir, context is src/autonomous-trust-services:
#    docker build -t autonomous-trust-services-test -f src/autonomous-trust-services/Dockerfile-test src/autonomous-trust-simulator
# Run as:
#    docker run --rm -u $(id -u):$(id -g) -v src/autonomous-trust-services:/app -it autonomous-trust-services-test

ARG REGISTRY_URL
FROM ${REGISTRY_URL}autonomous-trust-services-devel

WORKDIR /app
USER user
COPY --chown=user:user tests tests
COPY --chown=user:user tox.ini tox.ini
COPY --chown=user:user requirements.txt requirements.txt
COPY --chown=user:user tests_require.txt tests_require.txt
RUN mkdir -p /app/coverage

CMD ["sh", "-c", "python3 -m tests"]
