{% set name = "composable_paxos" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: eb119b8a0adced20188e3f038a7bc71a08a34bb98b97179e7a62371112be3c23

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: "https://github.com/cocagne/python-composable-paxos"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Implements the core Paxos algorithm as a set of composable classes"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
