# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/negotiation/task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/negotiation/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomous_trust.core.protobuf.processes import capabilities_pb2 as autonomous__trust_dot_core_dot_protobuf_dot_processes_dot_capabilities__pb2
from autonomous_trust.core.protobuf.structures import data_pb2 as autonomous__trust_dot_core_dot_protobuf_dot_structures_dot_data__pb2
from autonomous_trust.core.protobuf.structures import datetime_pb2 as autonomous__trust_dot_core_dot_protobuf_dot_structures_dot_datetime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5autonomous_trust/core/protobuf/negotiation/task.proto\x12*autonomous_trust.core.protobuf.negotiation\x1a;autonomous_trust/core/protobuf/processes/capabilities.proto\x1a\x34\x61utonomous_trust/core/protobuf/structures/data.proto\x1a\x38\x61utonomous_trust/core/protobuf/structures/datetime.proto\"\xbd\x02\n\x04Task\x12H\n\ncapability\x18\x01 \x01(\x0b\x32\x34.autonomous_trust.core.protobuf.processes.Capability\x12\x41\n\x04when\x18\x02 \x01(\x0b\x32\x33.autonomous_trust.core.protobuf.structures.DateTime\x12\x46\n\x08\x64uration\x18\x03 \x01(\x0b\x32\x34.autonomous_trust.core.protobuf.structures.TimeDelta\x12\x0f\n\x07timeout\x18\x04 \x01(\x04\x12=\n\x04\x61rgs\x18\x05 \x03(\x0b\x32/.autonomous_trust.core.protobuf.structures.Data\x12\x10\n\x08\x66lexible\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.negotiation.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=275
  _globals['_TASK']._serialized_end=592
# @@protoc_insertion_point(module_scope)
