name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python==3.10
  - mercurial-app
  - rsync
  - curl
  - libffi
  - maturin
  - tox
  - pytest
  - pytest-aiohttp
  - pytest-cov
  - pandoc
  - beautifulsoup4

  - aenum
  - libsass
  - networkx
  - psutil
  - pynacl
  - quart
  - ruamel.yaml

