name: autonomous_trust
channels:
  - conda-forge
  - defaults
dependencies:
  - aenum
  - aiofiles
  - beautifulsoup4
  - libsass
  - networkx
  - python>=3.10
  - quart
  - pytest
  - pynacl
  - ruamel_yaml
  - libffi
  - openssl
