/********************
 *  Copyright 2026 Sean M. Brennan and contributors
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *******************/

#include "negative_runner.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <sodium.h>
#include <uuid/uuid.h>

#include "identity/group.h"
#include "identity/identity.h"
#include "identity/identity_priv.h"
#include "network/net_message.h"

/* Provided by runner.c so adapters can resolve based_on into the JSON
 * mirror without threading the path through every API. */
extern const char *at_runner_corpus_json_root(void);

int at_neg_resolve_based_on(const char *corpus_json_root, const char *based_on,
                            char **out_path)
{
    if (corpus_json_root == NULL || based_on == NULL || out_path == NULL) return -1;
    size_t blen = strlen(based_on);
    /* Strip a trailing .yaml; append .json. The corpus mirror layout is
     * generated by tools/corpus_to_json.py and keeps the same relative
     * path with the suffix swapped. */
    const char *yaml_suffix = ".yaml";
    size_t ysuf = strlen(yaml_suffix);
    size_t stem_len = (blen >= ysuf && strcmp(based_on + blen - ysuf, yaml_suffix) == 0)
        ? blen - ysuf : blen;

    /* root '/' stem '.json' '\0' */
    size_t rlen = strlen(corpus_json_root);
    size_t total = rlen + 1 + stem_len + 5 + 1;
    char *p = malloc(total);
    if (p == NULL) return -1;
    snprintf(p, total, "%s/%.*s.json", corpus_json_root, (int)stem_len, based_on);
    *out_path = p;
    return 0;
}

int at_neg_load_base_case(const char *path, json_t **out_root)
{
    if (path == NULL || out_root == NULL) return -1;
    json_error_t err;
    json_t *root = json_load_file(path, 0, &err);
    if (root == NULL) return -1;
    *out_root = root;
    return 0;
}

static int _flip_signature_byte(const uint8_t *in_buf, size_t in_len,
                                int index, uint8_t **out_buf, size_t *out_len)
{
    json_error_t jerr;
    json_t *wire = json_loadb((const char *)in_buf, in_len, 0, &jerr);
    if (wire == NULL) return -2; /* skip: cannot mutate non-JSON */

    json_t *sig_node = json_object_get(wire, "signature");
    if (!json_is_string(sig_node)) {
        json_decref(wire);
        return -2; /* skip: no signature field */
    }
    const char *sig_hex = json_string_value(sig_node);
    int slen = (int)strlen(sig_hex);
    if (index < 0 || index >= slen) {
        json_decref(wire);
        return -1;
    }

    /* Toggle the low bit of one hex nibble — stays within the hex alphabet
     * so the consumer's hex decoder still accepts the byte. Byte-identical
     * to Python's _flip_signature_byte. */
    char ch = sig_hex[index];
    char flipped;
    if (ch >= '0' && ch <= '9') {
        flipped = (char)('0' + ((ch - '0') ^ 1));
    } else if (ch >= 'a' && ch <= 'f') {
        flipped = "abcdef"[(ch - 'a') ^ 1];
    } else if (ch >= 'A' && ch <= 'F') {
        flipped = "ABCDEF"[(ch - 'A') ^ 1];
    } else {
        json_decref(wire);
        return -2;
    }

    char *new_sig = malloc(slen + 1);
    if (new_sig == NULL) {
        json_decref(wire);
        return -1;
    }
    memcpy(new_sig, sig_hex, slen);
    new_sig[index] = flipped;
    new_sig[slen] = '\0';
    json_object_set_new(wire, "signature", json_string(new_sig));
    free(new_sig);

    char *dumped = json_dumps(wire, JSON_COMPACT);
    json_decref(wire);
    if (dumped == NULL) return -1;
    *out_len = strlen(dumped);
    *out_buf = (uint8_t *)dumped; /* malloc'd by jansson, free() compatible */
    return 0;
}

static int _flip_payload_byte(const uint8_t *in_buf, size_t in_len,
                              int index, uint8_t **out_buf, size_t *out_len)
{
    json_error_t jerr;
    json_t *wire = json_loadb((const char *)in_buf, in_len, 0, &jerr);
    if (wire == NULL) return -2;

    json_t *data_node = json_object_get(wire, "data");
    if (!json_is_string(data_node)) { json_decref(wire); return -2; }
    const char *b64 = json_string_value(data_node);
    int dlen = (int)strlen(b64);
    if (index < 0 || index >= dlen) { json_decref(wire); return -1; }

    char ch = b64[index];
    if (ch == '=') { json_decref(wire); return -2; }
    /* Move to the next character in the standard base64 alphabet so the
     * mutated string is still a well-formed b64. */
    static const char alphabet[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    const char *pos = strchr(alphabet, ch);
    if (pos == NULL) { json_decref(wire); return -2; }
    int pidx = (int)(pos - alphabet);
    char flipped = alphabet[(pidx + 1) % 64];

    char *new_b64 = malloc(dlen + 1);
    if (new_b64 == NULL) { json_decref(wire); return -1; }
    memcpy(new_b64, b64, dlen);
    new_b64[index] = flipped;
    new_b64[dlen] = '\0';
    json_object_set_new(wire, "data", json_string(new_b64));
    free(new_b64);

    char *dumped = json_dumps(wire, JSON_COMPACT);
    json_decref(wire);
    if (dumped == NULL) return -1;
    *out_len = strlen(dumped);
    *out_buf = (uint8_t *)dumped;
    return 0;
}

int at_neg_apply_mutation(const uint8_t *in_buf, size_t in_len,
                          json_t *mutation, uint8_t **out_buf, size_t *out_len)
{
    if (in_buf == NULL || mutation == NULL || out_buf == NULL || out_len == NULL)
        return -1;

    const char *op = json_string_value(json_object_get(mutation, "op"));
    const char *target = json_string_value(json_object_get(mutation, "target"));
    if (op == NULL || target == NULL) return -1;

    if (strcmp(op, "flip_byte") == 0 && strcmp(target, "signature") == 0) {
        json_t *idx_node = json_object_get(mutation, "index");
        int idx = json_is_integer(idx_node) ? (int)json_integer_value(idx_node) : 0;
        return _flip_signature_byte(in_buf, in_len, idx, out_buf, out_len);
    }

    if (strcmp(op, "flip_byte") == 0 && strcmp(target, "payload") == 0) {
        json_t *idx_node = json_object_get(mutation, "index");
        int idx = json_is_integer(idx_node) ? (int)json_integer_value(idx_node) : 0;
        return _flip_payload_byte(in_buf, in_len, idx, out_buf, out_len);
    }

    if (strcmp(op, "truncate") == 0 && strcmp(target, "wire_bytes") == 0) {
        json_t *idx_node = json_object_get(mutation, "index");
        if (!json_is_integer(idx_node)) return -1;
        int idx = (int)json_integer_value(idx_node);
        if (idx < 0 || (size_t)idx >= in_len) return -2;
        uint8_t *p = malloc((size_t)idx);
        if (p == NULL && idx > 0) return -1;
        if (idx > 0) memcpy(p, in_buf, (size_t)idx);
        *out_buf = p;
        *out_len = (size_t)idx;
        return 0;
    }

    if (strcmp(op, "inflate") == 0 && strcmp(target, "payload") == 0) {
        /* Replace the wire `data` field with base64 of N zero bytes.
         * Honest semantic — neither parser enforces a payload size
         * cap today (transport caps exist at net_transport_tcp.c:173
         * with NET_MSG_MAX_DATA=1MB, but they fire BEFORE the wire
         * parse, not inside it). The inflated envelope therefore
         * decodes cleanly; the signature was over the original
         * shorter payload, so verification fails. Test guarantees:
         * parser survives an O(N) larger input, signature verifier
         * correctly rejects. If a future hardening lands an
         * envelope-level size limit, this op's classify_op flips to
         * `payload_oversized` and the YAMLs follow. */
        json_t *size_node = json_object_get(mutation, "size");
        if (!json_is_integer(size_node)) return -1;
        long long sz_signed = (long long)json_integer_value(size_node);
        if (sz_signed < 1) return -1;
        size_t bin_len = (size_t)sz_signed;

        json_error_t jerr;
        json_t *wire = json_loadb((const char *)in_buf, in_len, 0, &jerr);
        if (wire == NULL) return -2;
        if (!json_is_object(wire)) { json_decref(wire); return -2; }

        unsigned char *bin = calloc(bin_len, 1);
        if (bin == NULL) { json_decref(wire); return -1; }
        size_t b64_buf_len = sodium_base64_encoded_len(bin_len, sodium_base64_VARIANT_ORIGINAL);
        char *b64 = malloc(b64_buf_len);
        if (b64 == NULL) { free(bin); json_decref(wire); return -1; }
        sodium_bin2base64(b64, b64_buf_len, bin, bin_len,
                          sodium_base64_VARIANT_ORIGINAL);
        free(bin);

        json_object_set_new(wire, "data", json_string(b64));
        free(b64);

        char *dumped = json_dumps(wire, JSON_COMPACT);
        json_decref(wire);
        if (dumped == NULL) return -1;
        *out_len = strlen(dumped);
        *out_buf = (uint8_t *)dumped;
        return 0;
    }

    if (strcmp(op, "replace") == 0 && strcmp(target, "wire_bytes") == 0) {
        /* Byte-identical to Python's apply_mutation replace/wire_bytes:
         * the entire wire buffer is swapped for a caller-supplied raw
         * byte sequence (hex-encoded in the YAML). Used to inject non-
         * JSON garbage; parser must reject as envelope_malformed. */
        const char *content_hex = json_string_value(
            json_object_get(mutation, "content_hex"));
        if (content_hex == NULL) return -1;
        size_t hlen = strlen(content_hex);
        if (hlen % 2 != 0) return -1;
        size_t n = hlen / 2;
        uint8_t *p = malloc(n + 1); /* +1 keeps allocation non-NULL when n=0 */
        if (p == NULL) return -1;
        for (size_t i = 0; i < n; i++) {
            unsigned int v;
            if (sscanf(content_hex + 2 * i, "%2x", &v) != 1) {
                free(p);
                return -1;
            }
            p[i] = (uint8_t)v;
        }
        *out_buf = p;
        *out_len = n;
        return 0;
    }

    if (strcmp(op, "drop_field") == 0 &&
        strncmp(target, "envelope.", 9) == 0) {
        const char *field = target + 9;
        json_error_t jerr;
        json_t *wire = json_loadb((const char *)in_buf, in_len, 0, &jerr);
        if (wire == NULL) return -2;
        if (!json_is_object(wire) ||
            json_object_get(wire, field) == NULL) {
            json_decref(wire);
            return -2;
        }
        json_object_del(wire, field);
        char *dumped = json_dumps(wire, JSON_COMPACT);
        json_decref(wire);
        if (dumped == NULL) return -1;
        *out_len = strlen(dumped);
        *out_buf = (uint8_t *)dumped;
        return 0;
    }

    return -2; /* unsupported op in v1 */
}

const char *at_neg_classify_op(json_t *mutation)
{
    const char *op = json_string_value(json_object_get(mutation, "op"));
    const char *target = json_string_value(json_object_get(mutation, "target"));
    if (op != NULL && strcmp(op, "truncate") == 0) return "envelope_truncated";
    if (op != NULL && target != NULL && strcmp(op, "flip_byte") == 0 &&
        (strcmp(target, "signature") == 0 || strcmp(target, "payload") == 0)) {
        return "signature_verification_failed";
    }
    /* inflate/payload: two regimes split on the parser-level size cap
     * (NET_MSG_MAX_DATA, 1 MB):
     *   - size below the cap: parser accepts, signature mismatches
     *     pre-inflation payload → signature_verification_failed.
     *   - size large enough to push the wire over the cap: parser's
     *     up-front size guard rejects before json_loadb runs →
     *     payload_oversized.
     * 768 KB raw * 1.33 (base64) ≈ 1.02 MB wire; tests should pin
     * sizes well below or well above 768 KB to stay clear of the
     * boundary. Mirrors the Python classify_op split. */
    if (op != NULL && target != NULL && strcmp(op, "inflate") == 0 &&
        strcmp(target, "payload") == 0) {
        json_int_t size = 0;
        json_t *size_j = json_object_get(mutation, "size");
        if (json_is_integer(size_j)) size = json_integer_value(size_j);
        if (size >= (json_int_t)(768 * 1024)) return "payload_oversized";
        return "signature_verification_failed";
    }
    return "envelope_malformed";
}

/* ------------------------------------------------------------------------- */
/* Wire-level negative runner                                                 */
/* ------------------------------------------------------------------------- */

/* Mint a deterministic Identity for negative-case wire signing. Keyed on
 * the participant id so all five protocols' negative cases get
 * byte-identical signers for the same `from` field. */
static int _make_signer_identity(const char *pid, identity_t **out) {
    /* SHA-256 of "at-conformance:neg:<pid>" gives 32 raw bytes; we use the
     * first 16 as the UUID (with the v4-shaped bits set). */
    char namestr[128];
    snprintf(namestr, sizeof(namestr), "at-conformance:neg:%s", pid);
    unsigned char sha[32];
    crypto_hash_sha256(sha, (const unsigned char *)namestr, strlen(namestr));
    uuid_t uuid;
    memcpy(uuid, sha, 16);
    uuid[6] = (uuid[6] & 0x0F) | 0x40;
    uuid[8] = (uuid[8] & 0x3F) | 0x80;

    char addr[ADDR_LEN + 1] = "10.0.90.1";
    char nickname[NAME_LEN + 1] = {0};
    snprintf(nickname, sizeof(nickname), "%s.neg", pid);

    if (identity_create(&uuid, addr, nickname, pid, out) != 0 || *out == NULL) {
        return -1;
    }

    /* Overwrite the randomly-generated keypairs with deterministic ones,
     * keyed on the participant id with role-suffixed labels. */
    char label[64];
    unsigned char digest[32];
    unsigned char hex_seed[crypto_sign_SEEDBYTES * 2 + 1];

    snprintf(label, sizeof(label), "at-conformance:neg:sig:%s", pid);
    crypto_hash_sha256(digest, (const unsigned char *)label, strlen(label));
    hexlify(digest, crypto_sign_SEEDBYTES, hex_seed);
    hex_seed[crypto_sign_SEEDBYTES * 2] = '\0';
    if (signature_init(&(*out)->signature, hex_seed,
                       crypto_sign_SEEDBYTES * 2) != 0)
        return -1;

    snprintf(label, sizeof(label), "at-conformance:neg:enc:%s", pid);
    crypto_hash_sha256(digest, (const unsigned char *)label, strlen(label));
    hexlify(digest, crypto_box_SEEDBYTES, hex_seed);
    hex_seed[crypto_box_SEEDBYTES * 2] = '\0';
    if (encryptor_init(&(*out)->encryptor, hex_seed,
                       crypto_box_SEEDBYTES * 2) != 0)
        return -1;
    return 0;
}

/* Look up `from` and `function` for the given step_id in a base scenario
 * JSON mirror. Returns 0 on success; -1 if not a source step or not found. */
static int _find_step(json_t *base_root, int step_id,
                      const char **out_from, const char **out_function) {
    json_t *data = json_object_get(base_root, "data");
    json_t *steps = json_object_get(data, "steps");
    if (!json_is_array(steps)) return -1;
    size_t n = json_array_size(steps);
    for (size_t i = 0; i < n; i++) {
        json_t *s = json_array_get(steps, i);
        json_t *id_node = json_object_get(s, "id");
        if (!json_is_integer(id_node)) continue;
        if ((int)json_integer_value(id_node) != step_id) continue;
        if (json_object_get(s, "in_response_to") != NULL) return -2;
        *out_from = json_string_value(json_object_get(s, "from"));
        *out_function = json_string_value(json_object_get(s, "function"));
        if (*out_from == NULL || *out_function == NULL) return -1;
        return 0;
    }
    return -1;
}

int at_neg_run_wire(const at_case_t *c, at_case_result_t *out_result) {
    char err[256] = {0};
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    const char *based_on = json_string_value(json_object_get(c->data, "based_on"));
    json_t *mutation = json_object_get(c->data, "mutation");
    json_t *expected = json_object_get(c->data, "expected");
    const char *expected_reason = json_string_value(
        json_object_get(expected, "reason_class"));
    if (based_on == NULL || mutation == NULL || expected_reason == NULL) {
        snprintf(err, sizeof(err), "negative case missing based_on/mutation/expected");
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }

    const char *json_root = at_runner_corpus_json_root();
    char *base_path = NULL;
    if (at_neg_resolve_based_on(json_root, based_on, &base_path) != 0) {
        snprintf(err, sizeof(err), "could not resolve based_on path %s", based_on);
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }
    json_t *base_root = NULL;
    int lc = at_neg_load_base_case(base_path, &base_root);
    free(base_path);
    if (lc != 0) {
        snprintf(err, sizeof(err), "could not load base case from %s", based_on);
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }

    json_t *step_node = json_object_get(mutation, "step_id");
    int step_id = json_is_integer(step_node) ? (int)json_integer_value(step_node) : 1;
    const char *from_id = NULL, *function = NULL;
    int find_rc = _find_step(base_root, step_id, &from_id, &function);
    if (find_rc != 0) {
        snprintf(err, sizeof(err),
                 "negative: step_id %d not a source step in %s", step_id, based_on);
        json_decref(base_root);
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }

    identity_t *sender = NULL;
    if (_make_signer_identity(from_id, &sender) != 0 || sender == NULL) {
        snprintf(err, sizeof(err), "could not build signer for %s", from_id);
        json_decref(base_root);
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }
    public_identity_t *sender_pub = NULL;
    if (identity_publish(sender, &sender_pub) != 0 || sender_pub == NULL) {
        snprintf(err, sizeof(err), "identity_publish failed");
        identity_free(sender);
        json_decref(base_root);
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }

    /* Build a generic signed Message: process = the case's protocol
     * (same as base_case.protocol), function from the step, data = "{}". */
    net_wire_msg_t msg = {0};
    strncpy(msg.process, c->protocol, PROC_NAME_LEN);
    msg.process[PROC_NAME_LEN] = '\0';
    msg.function = strdup(function);
    const char *empty = "{}";
    msg.data_len = strlen(empty);
    msg.data = malloc(msg.data_len);
    memcpy(msg.data, empty, msg.data_len);
    msg.to_whom.type = RECIPIENT_BROADCAST;
    memcpy(&msg.from_whom, sender_pub, sizeof(public_identity_t));
    msg.encrypt = false;

    uint8_t *clean = NULL;
    size_t clean_len = 0;
    if (net_message_to_wire(&msg, sender, &clean, &clean_len) != 0) {
        snprintf(err, sizeof(err), "net_message_to_wire failed");
        free(msg.function); free(msg.data);
        smrt_deref(sender_pub); identity_free(sender);
        json_decref(base_root);
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }
    free(msg.function);
    free(msg.data);

    uint8_t *mutated = NULL;
    size_t mutated_len = 0;
    int mrc = at_neg_apply_mutation(clean, clean_len, mutation, &mutated, &mutated_len);
    free(clean);
    if (mrc == -2) {
        /* Mutation op not supported by this build; skip the case. */
        smrt_deref(sender_pub); identity_free(sender);
        json_decref(base_root);
        at_case_result_set_skip(out_result, "mutation op not supported in v1");
        return 0;
    }
    if (mrc != 0) {
        snprintf(err, sizeof(err), "mutation application failed (rc=%d)", mrc);
        smrt_deref(sender_pub); identity_free(sender);
        json_decref(base_root);
        at_case_result_set_fail(out_result, 0, "AssertionError", err);
        return 0;
    }

    /* Categorize parser verdict. */
    const char *observed = NULL;
    net_wire_msg_t parsed = {0};
    int prc = net_message_from_wire(mutated, mutated_len, sender_pub, &parsed);
    if (prc != 0) {
        observed = at_neg_classify_op(mutation);
    } else if (!parsed.verified) {
        observed = "signature_verification_failed";
    } else {
        observed = "no_rejection_observed";
    }
    net_wire_msg_free(&parsed);
    free(mutated);
    smrt_deref(sender_pub);
    identity_free(sender);
    json_decref(base_root);

    clock_gettime(CLOCK_MONOTONIC, &t1);
    int duration_ms = (int)((t1.tv_sec - t0.tv_sec) * 1000
                            + (t1.tv_nsec - t0.tv_nsec) / 1000000);
    if (strcmp(observed, expected_reason) == 0) {
        at_case_result_set_pass(out_result, duration_ms);
    } else {
        snprintf(err, sizeof(err),
                 "reason_class mismatch: expected %s, observed %s",
                 expected_reason, observed);
        at_case_result_set_fail(out_result, duration_ms, "AssertionError", err);
    }
    return 0;
}
