# syntax=docker/dockerfile:1.3

# Runs AutonomousTrust Simulator from live sources

# Build from repo base dir:
#    docker build -t autonomous-trust-simulator-devel -f src/autonomous-trust-simulator/Dockerfile-devel .
# For rapid development, run as:
#    docker run --rm -u $(id -u):$(id -g) -v src/autonomous-trust-simulator:/app -it autonomous-trust-simulator-devel

FROM autonomous-trust-devel

WORKDIR /app
USER user
COPY --chown=user:user src/autonomous-trust/autonomous_trust/core autonomous_trust/core
COPY --chown=user:user src/autonomous-trust/autonomous_trust/__main__.py autonomous_trust/__main__.py
COPY --chown=user:user src/autonomous-trust-simulator/requirements.txt requirements.txt
COPY --chown=user:user src/autonomous-trust-simulator/pyproject.toml pyproject.toml
COPY --chown=user:user src/autonomous-trust-simulator/autonomous_trust/simulator autonomous_trust/simulator

RUN poetry lock  --no-update  # re-acquire dependencies (due to autonomous-trust image)
RUN poetry install

CMD ["sh", "-c", "conda run --live-stream -n autonomous_trust python3 -m autonomous_trust.simulator"]
