## conda-build *must* be called in the current directory (src/autonomous-trust-inspector)

{% set toml = load_file_data(os.path.abspath('./pyproject.toml')) %}  # fails early if wrong path
{% set project = toml.get('project', {}) %}
{% set name = project.get('name') %}
{% set version = project.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ./

build:
  noarch: python
  script: poetry build && {{PYTHON}} -m pip install ./dist/{{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv


requirements:
  build:
    - python==3.10
    - pip
    - poetry
  host:
    - python==3.10
    - pip
    - poetry
  run:
    - python>=3.10
    - autonomous-trust
    - autonomous-trust-services
    - autonomous-trust-inspector
    - numpy>=1.25.2
    - py-opencv>=4.8.0
    - imutils>=0.5.4
    - flask>=2.2.2
    - dash==2.6.2
    - dash-bootstrap-components>=1.5.0
