# syntax=docker/dockerfile:1.3

# Runs automated testing for AutonomousTrust

# Build from repo base dir, context is src/autonomous-trust:
#    docker build -t autonomous-trust-test -f src/autonomous-trust/Dockerfile-test src/autonomous-trust
# Run as:
#    docker run --rm -u $(id -u):$(id -g) -v src/autonomous-trust:/app -it autonomous-trust-test

FROM autonomous-trust-devel

WORKDIR /app
USER user
COPY --chown=user:user tests tests
COPY --chown=user:user tox.ini tox.ini
COPY --chown=user:user requirements.txt requirements.txt
COPY --chown=user:user tests_require.txt tests_require.txt
COPY --chown=user:user MANIFEST.in MANIFEST.in
RUN mkdir -p /app/coverage

CMD ["/bin/bash", "-c", "conda run --live-stream -n autonomous_trust tox 2>&1 | tee /app/tests/tox.log"]
