[tox]
envlist = at

[testenv]
deps =
    -rrequirements.txt
    -rtests_require.txt
commands = pytest --ignore=tests/local --cov=autonomous_trust --cov-append --cov-report=html:coverage

[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
addopts = -m "not slow"
filterwarnings =
    ignore::DeprecationWarning:pkg_resources:
