[tox]
envlist = at

[testenv]
deps =
    -rrequirements.txt
    -rtests_require.txt
commands = pytest --ignore=tests/local --ignore=conformance --cov=autonomous_trust --cov-append --cov-report=html:coverage

[testenv:conformance]
deps =
    -rrequirements.txt
    -rtests_require.txt
    jsonschema
    protobuf
    jcs
commands = pytest conformance/harness/python conformance/harness/common/tests tools/tests -v

[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
addopts = -m "not slow"
filterwarnings =
    ignore::DeprecationWarning:pkg_resources:
