# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/processes/capabilities.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/processes/capabilities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomous_trust.core.protobuf.structures import map_pb2 as autonomous__trust_dot_core_dot_protobuf_dot_structures_dot_map__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;autonomous_trust/core/protobuf/processes/capabilities.proto\x12(autonomous_trust.core.protobuf.processes\x1a\x33\x61utonomous_trust/core/protobuf/structures/map.proto\"s\n\nCapability\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x45\n\targ_types\x18\x03 \x01(\x0b\x32\x32.autonomous_trust.core.protobuf.structures.DataMap\"\xd4\x01\n\x10PeerCapabilities\x12X\n\x07listing\x18\x01 \x03(\x0b\x32G.autonomous_trust.core.protobuf.processes.PeerCapabilities.PeerCapacity\x1a\x66\n\x0cPeerCapacity\x12\x0c\n\x04peer\x18\x01 \x01(\t\x12H\n\ncapability\x18\x02 \x03(\x0b\x32\x34.autonomous_trust.core.protobuf.processes.Capabilityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.processes.capabilities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITY']._serialized_start=158
  _globals['_CAPABILITY']._serialized_end=273
  _globals['_PEERCAPABILITIES']._serialized_start=276
  _globals['_PEERCAPABILITIES']._serialized_end=488
  _globals['_PEERCAPABILITIES_PEERCAPACITY']._serialized_start=386
  _globals['_PEERCAPABILITIES_PEERCAPACITY']._serialized_end=488
# @@protoc_insertion_point(module_scope)
