name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python==3.13.*
  - poetry
  - maturin
  - docker-py
  - gitpython>=3.1.35
  - types-protobuf>=6.32.1
  - pexpect
  - rsync
  - curl
  - libffi
  - tox
  - pandoc
  - beautifulsoup4
  - pytest
  - pytest-aiohttp
  - pytest-asyncio
  - pytest-cov
  - go
  - napkin
  - pylint
  - nodejs
  - clang
  - clangxx
  - lld
  - git
  - lcov
  - llvmdev
  - opam
  - autoconf
  - gmp
  - pcre2
  - sqlite
  - automake
  - libtool
  - pkg-config
  - libexpat
  - testcontainers
  - jsonschema
  - ruamel.yaml
