name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python==3.13.*
  - icontract
  - psutil
  - pynacl
  - python-dateutil
  - protobuf>=6.33.5
  - libprotobuf>=6.33.5
  - protobuf-c>=1.5.2
  - aenum
  - libsass
  - setuptools
  - networkx
  - quart>=0.19.5
  - numpy
  - dill
  - py-opencv
  - imutils
  - msgpack-numpy
  - geopy
  - utm
  - dash>=4.0.0
  - dash-bootstrap-components>=2.0.0
  - more-itertools>=10.6.0
  - jsbeautifier>=1.15.4
  - dash-extensions>=2.0.4
  - dash-iconify
  - plotly
  - werkzeug>=3.0.3
  - flask>=3.0,<3.2
  - flask-caching>=2.3.1
  - eventlet
  - absl-py
  - python-flatbuffers
  - python-sounddevice
  - cmake
  - libuuid
  - libsodium
  - jansson
  - check
  - websockets
  - pydantic
  - pyyaml
  - pytorch
  - torchvision
  - ultralytics
  - ultralytics-thop
  - pyproj
  - cryptography
  - pip
  # pip packages currently disabled:
  #   - mediapipe
  #   - parrot-olympe  # uses an old version of protobuf
