name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - pip
  - icontract
  - psutil
  - pynacl
  - python-dateutil
  - ruamel.yaml
  - protobuf>=6.31.1
  - types-protobuf>=6.31.1
  - libprotobuf>=6.31.1,<6.31.2.0a0
  - protobuf-c==1.5.2
  - aenum
  - libsass
  - networkx
  - quart==0.18.3
  - numpy
  - dill
  - py-opencv
  - imutils
  - msgpack-numpy
  - geopy
  - utm
  - dash==2.14.2
  - dash-bootstrap-components
  - more-itertools==9.0.0
  - jsbeautifier==1.14.3
  - dash-extensions
  - dash-iconify
  - plotly
  - werkzeug==2.2.2
  - flask<=2.2.2
  - flask-caching==2.0.2
  - eventlet
  - absl-py
  - python-flatbuffers
  - python-sounddevice
  - cmake
  - libuuid
  - libsodium
  - jansson
  - check
  - websockets
  - pydantic
  - cxx-compiler
  - pip:
      #- mediapipe
      #- parrot-olympe # uses an old version of protobuf
