name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python==3.10
  - mercurial-app
  - libffi
  - maturin
  - tox
  - rsync
  - pytest
  - pytest-aiohttp
  - pytest-cov

  - aenum
  - libsass
  - networkx
  - pebble
  - pynacl
  - quart
  - ruamel.yaml

