name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - aenum
  - aiofiles
  - beautifulsoup4
  - libffi
  - libsass
  - mercurial-app
  - networkx
  - openssl
  - pebble
  - pip
  - pytest
  - quart
  - rsync
  - ruamel.yaml
