# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/identity/history.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/identity/history.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomous_trust.core.protobuf.identity import identity_pb2 as autonomous__trust_dot_core_dot_protobuf_dot_identity_dot_identity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5autonomous_trust/core/protobuf/identity/history.proto\x12\'autonomous_trust.core.protobuf.identity\x1a\x36\x61utonomous_trust/core/protobuf/identity/identity.proto\"a\n\x06IdBlob\x12\x12\n\noriginator\x18\x01 \x01(\x0c\x12\x43\n\x08identity\x18\x02 \x01(\x0b\x32\x31.autonomous_trust.core.protobuf.identity.Identityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.identity.history_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDBLOB']._serialized_start=154
  _globals['_IDBLOB']._serialized_end=251
# @@protoc_insertion_point(module_scope)
