# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/identity/identity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/identity/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6autonomous_trust/core/protobuf/identity/identity.proto\x12\'autonomous_trust.core.protobuf.identity\"\x1d\n\tEncryptor\x12\x10\n\x08hex_seed\x18\x01 \x01(\x0c\"\x1d\n\tSignature\x12\x10\n\x08hex_seed\x18\x01 \x01(\x0c\"\xc9\x01\n\x08Identity\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x10\n\x08\x66ullname\x18\x03 \x01(\t\x12\x45\n\tsignature\x18\x04 \x01(\x0b\x32\x32.autonomous_trust.core.protobuf.identity.Signature\x12\x45\n\tencryptor\x18\x05 \x01(\x0b\x32\x32.autonomous_trust.core.protobuf.identity.Encryptor\"m\n\x05Group\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x45\n\tencryptor\x18\x03 \x01(\x0b\x32\x32.autonomous_trust.core.protobuf.identity.Encryptorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.identity.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCRYPTOR']._serialized_start=99
  _globals['_ENCRYPTOR']._serialized_end=128
  _globals['_SIGNATURE']._serialized_start=130
  _globals['_SIGNATURE']._serialized_end=159
  _globals['_IDENTITY']._serialized_start=162
  _globals['_IDENTITY']._serialized_end=363
  _globals['_GROUP']._serialized_start=365
  _globals['_GROUP']._serialized_end=474
# @@protoc_insertion_point(module_scope)
