# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/structures/data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/structures/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4autonomous_trust/core/protobuf/structures/data.proto\x12)autonomous_trust.core.protobuf.structures\"\xbe\x01\n\x04\x44\x61ta\x12\x41\n\x04type\x18\x01 \x01(\x0e\x32\x33.autonomous_trust.core.protobuf.structures.DataType\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0f\n\x05intgr\x18\x03 \x01(\x03H\x00\x12\x0f\n\x05uintr\x18\x04 \x01(\x04H\x00\x12\x10\n\x06\x66lt_pt\x18\x05 \x01(\x01H\x00\x12\x0c\n\x02\x62l\x18\x06 \x01(\x08H\x00\x12\r\n\x03str\x18\x07 \x01(\tH\x00\x12\r\n\x03\x62yt\x18\x08 \x01(\x0cH\x00\x42\x05\n\x03\x64\x61t*_\n\x08\x44\x61taType\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03INT\x10\x01\x12\x08\n\x04UINT\x10\x02\x12\t\n\x05\x46LOAT\x10\x03\x12\x08\n\x04\x42OOL\x10\x04\x12\n\n\x06STRING\x10\x05\x12\t\n\x05\x42YTES\x10\x06\x12\n\n\x06OBJECT\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.structures.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=292
  _globals['_DATATYPE']._serialized_end=387
  _globals['_DATA']._serialized_start=100
  _globals['_DATA']._serialized_end=290
# @@protoc_insertion_point(module_scope)
