# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/structures/datetime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/structures/datetime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8autonomous_trust/core/protobuf/structures/datetime.proto\x12)autonomous_trust.core.protobuf.structures\"\xb0\x01\n\x08\x44\x61teTime\x12\x12\n\nnanosecond\x18\x01 \x01(\r\x12\x0e\n\x06second\x18\x02 \x01(\r\x12\x0e\n\x06minute\x18\x03 \x01(\r\x12\x0c\n\x04hour\x18\x04 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x05 \x01(\r\x12\r\n\x05month\x18\x06 \x01(\r\x12\x0c\n\x04year\x18\x07 \x01(\r\x12\x0f\n\x07weekday\x18\x08 \x01(\r\x12\x13\n\x0b\x64\x61y_of_year\x18\t \x01(\r\x12\x12\n\nutc_offset\x18\n \x01(\x02\"?\n\tTimeDelta\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\x12\x12\x0f\n\x07seconds\x18\x02 \x01(\r\x12\x13\n\x0bnanoseconds\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.structures.datetime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATETIME']._serialized_start=104
  _globals['_DATETIME']._serialized_end=280
  _globals['_TIMEDELTA']._serialized_start=282
  _globals['_TIMEDELTA']._serialized_end=345
# @@protoc_insertion_point(module_scope)
