# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/structures/map.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/structures/map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomous_trust.core.protobuf.structures import data_pb2 as autonomous__trust_dot_core_dot_protobuf_dot_structures_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3autonomous_trust/core/protobuf/structures/map.proto\x12)autonomous_trust.core.protobuf.structures\x1a\x34\x61utonomous_trust/core/protobuf/structures/data.proto\"\xb4\x01\n\x07\x44\x61taMap\x12L\n\x03map\x18\x01 \x03(\x0b\x32?.autonomous_trust.core.protobuf.structures.DataMap.DataMapEntry\x1a[\n\x0c\x44\x61taMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12>\n\x05value\x18\x02 \x01(\x0b\x32/.autonomous_trust.core.protobuf.structures.Datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.structures.map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAMAP']._serialized_start=153
  _globals['_DATAMAP']._serialized_end=333
  _globals['_DATAMAP_DATAMAPENTRY']._serialized_start=242
  _globals['_DATAMAP_DATAMAPENTRY']._serialized_end=333
# @@protoc_insertion_point(module_scope)
