# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomous_trust/core/protobuf/structures/merkle.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomous_trust/core/protobuf/structures/merkle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6autonomous_trust/core/protobuf/structures/merkle.proto\x12)autonomous_trust.core.protobuf.structures\x1a\x19google/protobuf/any.proto\"\xba\x02\n\nMerkleNode\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x45\n\x06parent\x18\x02 \x01(\x0b\x32\x35.autonomous_trust.core.protobuf.structures.MerkleNode\x12\x43\n\x04left\x18\x03 \x01(\x0b\x32\x35.autonomous_trust.core.protobuf.structures.MerkleNode\x12\x44\n\x05right\x18\x04 \x01(\x0b\x32\x35.autonomous_trust.core.protobuf.structures.MerkleNode\x12\x0b\n\x03red\x18\x05 \x01(\x08\x12\x0c\n\x04uuid\x18\x06 \x01(\x0c\x12\x0e\n\x06\x64igest\x18\x07 \x01(\r\x12\"\n\x04\x62lob\x18\x08 \x01(\x0b\x32\x14.google.protobuf.Any\"r\n\nMerkleTree\x12\x43\n\x04root\x18\x01 \x01(\x0b\x32\x35.autonomous_trust.core.protobuf.structures.MerkleNode\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x11\n\tsuperHash\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomous_trust.core.protobuf.structures.merkle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MERKLENODE']._serialized_start=129
  _globals['_MERKLENODE']._serialized_end=443
  _globals['_MERKLETREE']._serialized_start=445
  _globals['_MERKLETREE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
