/********************
 *  Copyright 2026 TekFive, Inc., Sean M. Brennan, and contributors
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *******************/

#ifndef NET_MESSAGE_H
#define NET_MESSAGE_H

/** @addtogroup internal_network
 *  @{
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#include "identity/identity.h"
#include "utilities/util.h"
#include "network/net_wire_format.h"

#define NET_MSG_MAX_DATA (1024 * 1024)  /* 1 MB max wire message */

/** Length of a trace_id string: 32 hex chars + NUL, matching Python's
 *  `uuid.uuid4().hex` format (which omits the separator hyphens). */
#define NET_TRACE_ID_LEN 32

/** @brief Whether a wire message is addressed to one peer or to all. */
typedef enum {
    RECIPIENT_PEER = 0,     /**< @c target.peer holds the intended recipient. */
    RECIPIENT_BROADCAST = 1 /**< Message is broadcast to the group; @c target is unused. */
} recipient_type_t;

/** @brief Recipient descriptor discriminated by @ref recipient_type_t. */
typedef struct {
    recipient_type_t type;      /**< Discriminates @c target. */
    union {
        public_identity_t peer; /**< Live when @c type == @ref RECIPIENT_PEER. */
    } target;
} net_recipient_t;

/**
 * @brief Decoded representation of a network wire message.
 *
 * @c signature is only meaningful when @c has_signature is @c true;
 * otherwise its bytes are uninitialized. @c verified is set by the receiver
 * after a successful signature check and is never serialized onto the wire.
 */
typedef struct {
    char process[PROC_NAME_LEN + 1];        /**< Destination process name (NUL-terminated). */
    char *function;                         /**< Heap-allocated function selector; freed by net_wire_msg_free(). */
    uint8_t *data;                          /**< Heap-allocated payload; freed by net_wire_msg_free(). */
    size_t data_len;                        /**< Length of @c data in bytes. */
    char trace_id[NET_TRACE_ID_LEN + 1];    /**< 32-char hex correlation id (NUL-terminated). Auto-generated by net_message_to_wire when empty; preserved across a parse hop. */
    net_recipient_t to_whom;                /**< Recipient (peer or broadcast). */
    public_identity_t from_whom;            /**< Declared sender identity. */
    int from_rank;                          /**< Sender topology rank (envelope field "from_rank"; mirrors Python from_whom._rank). 0 = unknown. */
    bool encrypt;                           /**< Request per-peer encryption of @c data. */
    uint8_t signature[crypto_sign_BYTES];   /**< Ed25519 signature bytes (valid iff @c has_signature). */
    bool has_signature;                     /**< Discriminant: true when @c signature is populated. */
    bool verified;                          /**< Receiver-side flag after signature verification (not wire-serialized). */
} net_wire_msg_t;

/**
 * @brief A frame arrived in an envelope format this context does not speak.
 *
 * Its own error number, declared HERE rather than kept private to
 * net_message.c, because the distinction is the caller's business: a cohort
 * misprovisioned into two formats presents as one peer having gone silent, and
 * only a counter that says "foreign format" rather than "bad message" explains
 * it. Read it off `_exception.errnum` after a non-zero return (EXCEPTION always
 * returns -1). NOT a signal to retry with the other parser -- see
 * doc/architecture/network-wire-format.md.
 */
#define ENET_WIRE_FORMAT 233

/**
 * @brief Serialize a wire message to JSON, optionally signing it.
 * @param signer If non-NULL, the message is signed with this identity's private key.
 */
/*@
  requires msg == \null || \valid(msg);
  requires \valid(wire_out);
  requires \valid(wire_len);
  allocates *wire_out;
  behavior null_msg:
    assumes msg == \null;
    ensures \result != 0;
  behavior success:
    assumes msg != \null;
    ensures \result == 0 ==> *wire_out != \null && *wire_len > 0;
  behavior failure:
    assumes msg != \null;
    ensures \result != 0;
  disjoint behaviors null_msg, success;
*/
int net_message_to_wire(const net_wire_msg_t *msg, const identity_t *signer,
                        uint8_t **wire_out, size_t *wire_len);

/**
 * @brief Parse a wire-format buffer into a @ref net_wire_msg_t.
 *
 * If @p peer is non-NULL and the wire data carries a signature, the
 * signature is verified against @p peer's public key and @c msg_out->verified
 * is set accordingly.
 *
 * @param[in]  data     Serialized wire bytes.
 * @param[in]  len      Length of @p data.
 * @param[in]  peer     Purported sender (used for signature verification); may be NULL.
 * @param[out] msg_out  Receives the parsed message (own's heap fields; free with net_wire_msg_free()).
 * @return 0 on successful parse, non-zero on malformed input or signature failure.
 */
/*@
  requires data == \null || \valid_read(data + (0 .. len - 1));
  requires msg_out == \null || \valid(msg_out);
  assigns *msg_out;
  behavior null_args:
    assumes data == \null || msg_out == \null;
    ensures \result != 0;
  behavior success:
    assumes data != \null && msg_out != \null;
    ensures \result == 0 || \result != 0;
  disjoint behaviors;
*/
int net_message_from_wire(const uint8_t *data, size_t len,
                          const public_identity_t *peer, net_wire_msg_t *msg_out);

/**
 * @brief Release heap fields (@c function, @c data) inside a @ref net_wire_msg_t.
 *
 * Does not free @p msg itself. Safe to call with NULL.
 */
/*@
  requires msg == \null || \valid(msg);
  behavior null_msg:
    assumes msg == \null;
    assigns \nothing;
  behavior valid_msg:
    assumes msg != \null;
    assigns msg->function, msg->data;
    frees msg->function, msg->data;
    ensures msg->function == \null;
    ensures msg->data == \null;
  disjoint behaviors;
  complete behaviors;
*/
void net_wire_msg_free(net_wire_msg_t *msg);

/**
 * @brief Serialize a wire message in @p fmt, optionally signing it.
 *
 * @ref net_message_to_wire is this with @ref NET_WIRE_JSON, kept as its own
 * name because every caller that has no group in hand (discovery, tests) is
 * asking for JSON specifically.
 *
 * The SIGNED bytes do not depend on @p fmt: both forms sign the canonical
 * "<process>|<function>|<base64(data)>" pre-image, so the two encodings of one
 * message carry the same signature and re-encoding cannot invalidate it.
 */
/*@
  requires msg == \null || \valid(msg);
  requires \valid(wire_out);
  requires \valid(wire_len);
  allocates *wire_out;
  behavior null_msg:
    assumes msg == \null;
    ensures \result != 0;
  behavior success:
    assumes msg != \null;
    ensures \result == 0 ==> *wire_out != \null && *wire_len > 0;
  behavior failure:
    assumes msg != \null;
    ensures \result != 0;
  disjoint behaviors null_msg, success;
*/
int net_message_to_wire_fmt(const net_wire_msg_t *msg, const identity_t *signer,
                            net_wire_format_t fmt,
                            uint8_t **wire_out, size_t *wire_len);

/**
 * @brief Parse a wire buffer KNOWN to be in @p fmt.
 *
 * The format is stated by the caller -- the group the frame arrived on, or
 * JSON outside a group -- and never inferred from the bytes. A frame whose
 * leading byte disagrees is refused with @c ENET_WIRE_FORMAT before the
 * parser for the other format sees it, so the caller can count and log the
 * event (a cohort misprovisioned into two formats otherwise presents as
 * unexplained silence). @ref net_message_from_wire is this with
 * @ref NET_WIRE_JSON.
 */
/*@
  requires data == \null || \valid_read(data + (0 .. len - 1));
  requires msg_out == \null || \valid(msg_out);
  assigns *msg_out;
  behavior null_args:
    assumes data == \null || msg_out == \null;
    ensures \result != 0;
  behavior success:
    assumes data != \null && msg_out != \null;
    ensures \result == 0 || \result != 0;
  disjoint behaviors;
*/
int net_message_from_wire_fmt(const uint8_t *data, size_t len,
                              const public_identity_t *peer,
                              net_wire_format_t fmt, net_wire_msg_t *msg_out);

/**
 * @brief The protobuf envelope specifically (magic byte + packed NetMessage).
 *
 * Callers normally go through @ref net_message_to_wire_fmt; these are exposed
 * because the JSON pair is, and because the tests drive each encoding
 * directly.
 */
int net_message_to_wire_proto(const net_wire_msg_t *msg, const identity_t *signer,
                              uint8_t **wire_out, size_t *wire_len);

/** @brief Inverse of @ref net_message_to_wire_proto. See @ref net_message_from_wire_fmt. */
int net_message_from_wire_proto(const uint8_t *data, size_t len,
                                const public_identity_t *peer,
                                net_wire_msg_t *msg_out);


/** @} */ /* end of internal_network */

#endif  /* NET_MESSAGE_H */
