# syntax=docker/dockerfile:1.3

# Runs AutonomousTrust Inspector from live sources

# Build from repo base dir:
#    docker build -t autonomous-trust-inspector-devel -f src/autonomous-trust-inspect/Dockerfile-devel .
# For rapid development, run as:
#    docker run --rm -u $(id -u):$(id -g) -v src/autonomous-trust-inspect:/app -it autonomous-trust-inspector-devel

FROM autonomous-trust-devel

WORKDIR /app
USER user
COPY --chown=user:user src/autonomous-trust/autonomous_trust/core autonomous_trust/core
COPY --chown=user:user src/autonomous-trust/autonomous_trust/__main__.py autonomous_trust/__main__.py
COPY --chown=user:user src/autonomous-trust-inspector/requirements.txt requirements.txt
COPY --chown=user:user src/autonomous-trust-inspector/pyproject.toml pyproject.toml
COPY --chown=user:user src/autonomous-trust-inspector/autonomous_trust/inspector autonomous_trust/inspector

RUN poetry lock  --no-update  # re-acquire dependencies (due to autonomous-trust image)
RUN poetry install

CMD ["sh", "-c", "conda run --live-stream -n autonomous_trust python3 -m autonomous_trust.inspector"]
