## conda-build *must* be called in the current directory (src/autonomous-trust-inspector)

{% set toml = load_file_data(os.path.abspath('./pyproject.toml')) %}  # fails early if wrong path
{% set project = toml.get('project', {}) %}
{% set name = project.get('name') %}
{% set version = project.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ./

build:
  noarch: python
  script: poetry build && {{PYTHON}} -m pip install ./dist/{{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv


requirements:
  build:
    - python==3.10
    - pip
    - poetry
  host:
    - python==3.10
    - pip
    - poetry
  run:
    - python>=3.10
    - autonomous-trust
    - aenum>=3.1.11
    - libsass>=0.22.0
    - networkx>=3.0
    - quart>=0.18.3
    - dash==2.6.2
    - flask>=2.2.2
    - plotly>=5.9.0
    - dash-bootstrap-components>=1.5.0
#    - dash-iconify>=0.1.2  # pip only
