# syntax=docker/dockerfile:1.3
# ******************
#  Copyright 2023 TekFive, Inc., Sean M. Brennan, and contributors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ******************

# Runs a custom AutonomousTrust module from (all) live sources

# Build from repo base dir:
#    docker build -t autonomous-trust-full-devel  -f src/Dockerfile-devel .
# For rapid development, run as:
#    docker run --rm -u $(id -u):$(id -g) -v examples/requestor/requestor.py:/app/requestor.py -e AUTONOMOUS_TRUST_EXE=requestor.py -it autonomous-trust-full-devel

ARG REGISTRY_URL
ARG IMAGE_TAG
FROM ${REGISTRY_URL}autonomous-trust-devel${IMAGE_TAG}

USER root
RUN apt-get update && apt-get install -y libgl1 libglx-mesa0

WORKDIR /app
USER user

COPY --chown=user:user src/autonomous-trust/autonomous_trust/core autonomous_trust/core
COPY --chown=user:user src/autonomous-trust-inspector/autonomous_trust/inspector autonomous_trust/inspector
COPY --chown=user:user src/autonomous-trust-services/autonomous_trust/services autonomous_trust/services
COPY --chown=user:user src/autonomous-trust-simulator/autonomous_trust/simulator autonomous_trust/simulator

# update and install any new dependencies from environment.yml
COPY --chown=user:user config/cfg/environment.yml /build/config/cfg/environment.yml
COPY --chown=user:user config/cfg/environment.yml ./environment.yml
COPY --chown=user:user scripts/*.sh scripts/
RUN scripts/setup-dev.sh --update
