version: '3.2'
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/registry.crt
      REGISTRY_HTTP_TLS_KEY: /run/secrets/registry.key
    volumes:
      - type: bind
        source: $DOCKER_ROOT/registry
        target: /var/lib/registry
    secrets:
      - registry.crt
      - registry.key
    networks:
      - default
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
          - 'node.platform.os == linux'

secrets:
  registry.crt:
    file: $DOCKER_ROOT/certs/registry.crt
  registry.key:
    file: $DOCKER_ROOT/certs/registry.key