# syntax=docker/dockerfile:1.3

# Runs a custom AutonomousTrust module from (all) live sources

# Build from repo base dir:
#    docker build -t autonomous-trust-full-devel  -f src/Dockerfile-devel .
# For rapid development, run as:
#    docker run --rm -u $(id -u):$(id -g) -v examples/requestor/requestor.py:/app/requestor.py -e AUTONOMOUS_TRUST_EXE=requestor.py -it autonomous-trust-full-devel

ARG REGISTRY_URL
ARG IMAGE_TAG
FROM ${REGISTRY_URL}autonomous-trust-devel${IMAGE_TAG}

USER root
RUN apt-get update && apt-get install -y libgl1 libglx-mesa0

WORKDIR /app
USER user

COPY --chown=user:user src/autonomous-trust/autonomous_trust/core autonomous_trust/core
COPY --chown=user:user src/autonomous-trust-inspector/autonomous_trust/inspector autonomous_trust/inspector
COPY --chown=user:user src/autonomous-trust-services/autonomous_trust/services autonomous_trust/services
COPY --chown=user:user src/autonomous-trust-simulator/autonomous_trust/simulator autonomous_trust/simulator

# update and install any new dependencies from environment.yaml
COPY --chown=user:user config/cfg/environment.yaml /build/config/cfg/environment.yaml
COPY --chown=user:user ./*.sh .
RUN ./setup-dev.sh --update
